#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: infra-config
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./clusterconfig
#  prune: true
#  validation: client
#
##apiVersion: kustomize.config.k8s.io/v1beta1
##kind: Kustomization
##metadata:
##  name: int-config
##  namespace: flux-system
##resources:
##  - int-config
