apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus

configMapGenerator:
  - name: flux-prometheus2
    files:
      - values.yaml=flux-statsd-exporter.yaml
configurations:
  - kustomizeconfig.yaml
