apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
#  - ../base/rucio-daemons
  - ../base/rucio-server
#  - ../base/rucio-webui
#  - ../base/rucio-probes
#  - ../base/cms-rucio-consistency
#  - ../base/cms-rucio-traces
#  - ../base/cms-rucio-cronjobs   # Not needed, no master config file
# Shut it all down on flux - working fine
#  - rucio-server-helm.yaml
#  - rucio-daemons-helm.yaml
#  - rucio-webui-helm.yaml
#  - rucio-probes-helm.yaml
#  - cms-rucio-cronjobs.yaml
#  - cms-rucio-traces.yaml
#  - cms-rucio-consistency.yaml

# Yet to be implemented:
# loadtest
# webdav loadtest
