apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
resources:
  - ../base
  - ../base/rucio-daemons
  - ../base/rucio-server
  - ../base/rucio-webui
  - ../base/rucio-probes
  - ../base/cms-rucio-consistency
  - ../base/cms-rucio-traces
#  - ../base/cms-rucio-cronjobs   # Not needed, no master config file
# Shut it all down on flux - working fine
  - rucio-server-helm.yaml
#  - rucio-daemons-helm.yaml
#  - rucio-webui-helm.yaml
#  - rucio-probes-helm.yaml
#  - cms-rucio-cronjobs.yaml
#  - cms-rucio-traces.yaml
#  - cms-rucio-consistency.yaml

# Yet to be implemented:
# loadtest
# webdav loadtest

configMapGenerator:
  - name: flux-rucio-server
    files:
      - values.yaml=flux-rucio-server.yaml
  - name: flux-rucio-daemons
    files:
      - values.yaml=flux-rucio-daemons.yaml
  - name: flux-rucio-webui
    files:
      - values.yaml=flux-rucio-webui.yaml
  - name: flux-rucio-probes
    files:
      - values.yaml=flux-rucio-probes.yaml
  - name: flux-release
    files:
      - values.yaml=flux-release.yaml
  - name: flux-consistency
    files:
      - values.yaml=flux-consistency.yaml
  - name: flux-consistency-jobs
    files:
      - values.yaml=flux-consistency-jobs.yaml
  - name: flux-cronjobs
    files:
      - values.yaml=flux-cronjobs.yaml
configurations:
  - kustomizeconfig.yaml
